"""Type stub for the PyO3 bridge in ``rust/bindings/python/src/lib.rs``.

maturin only picks stubs up from the directory holding ``pyproject.toml``, which
is why this lives here; keep it in step with the Rust module.
"""

from typing import Final

PROTOCOL_VERSION: Final[int]

class BridgeError(Exception):
    """Typed failure; ``args`` is ``(code, retryable, field)`` and never payload text."""

    args: tuple[str, bool, str | None]

class Command:
    @property
    def protocol_version(self) -> int: ...
    @property
    def command_id(self) -> str: ...
    @property
    def scope_id(self) -> str: ...
    @property
    def device_id(self) -> str: ...
    @property
    def local_sequence(self) -> str: ...
    @property
    def command_type(self) -> str: ...
    @property
    def command_version(self) -> int: ...
    @property
    def entity_id(self) -> str: ...
    @property
    def executable(self) -> bool: ...
    @property
    def unsupported_reason(self) -> str | None: ...
    def to_bytes(self) -> bytes: ...

class Runtime:
    def __init__(self, protocol_version: int) -> None: ...
    @property
    def is_open(self) -> bool: ...
    def persistence(self, kind: str, data: bytes) -> bytes: ...
    def close(self) -> None: ...
    def decode_command(self, data: bytes) -> Command: ...
    def decide(
        self, read_set: bytes, envelope: bytes, receipts: bytes, inputs: bytes
    ) -> bytes: ...
    def query(self, read_set: bytes, query: bytes, inputs: bytes) -> bytes: ...
